### ISSUE TITLE
Fix memory leak

### ISSUE THREAD

**Issue by rvosa** [rvosa/bio-phylo#16]
Objects that are inserted in Bio::Phylo::Listable containers appear to stay alive even beyond the point when the container goes out of scope and is cleaned up. This causes a memory leak that should be fixed. The behaviour is demonstrated in t/37-memory.t, which skips the problematic tests as of commit 340f24be5404bd9ce3d2a56cc406243fdc0d3d39

**Comment by moritz** [comment]
FWIW all tests pass for me, even when I remove the last remaining `skip` in t/37-memory. Can this issue be closed?
