### ISSUE TITLE
unable to reroot trees

### ISSUE THREAD

**Issue by dbaurain** [rvosa/bio-phylo#30]
Hi Rutger,

I use `Bio::Phylo` for all my tree parsing and manipulation needs in Perl but one thing: rerooting. Apparently, the corresponding methods (`set_root_below` and its wrapper `reroot`) are broken. I did try to fix this myself, but it looks quite complex without fully understanding the way tree are modelled... and frankly, the reason I use your otherwise very nice module is to avoid thinking about that :-) Therefore, what would be your advice to reroot trees (either on leaves or on internal nodes) using `Bio::Phylo`?

Cheers,
Denis

**Comment by rvosa** [comment]
Hi Denis,

which version are you using? I re-implemented the re-rooting fairly
recently because there were, indeed, bugs in earlier versions.

Cheers,
Rutger

**Comment by dbaurain** [comment]
Thank you for your fast answer, Rutger.
I use the following version:

$ cpanm Bio::Phylo
Bio::Phylo is up to date. (0.58)

Cheers,
Denis

**Comment by rvosa** [comment]
Ah, so you installed this from CPAN, correct? I haven't pushed out the new
algorithm to CPAN yet. You have two options:

1. install from the github repository: cpanm git://
github.com/rvosa/bio-phylo.git

2. replacing the method for set_root_below (in NodeRole.pm) with the one
from github:
https://github.com/rvosa/bio-phylo/blob/master/lib/Bio/Phylo/Forest/NodeRole.pm#L440-L521

Apologies for the hassle: I should really push out a new release but I
haven't got around to it in a while.

**Comment by dbaurain** [comment]
Thank you, Rutger. That was very helpful!

However, it would be great if you could upload your latest release to CPAN as Bio::Phylo is a dependency of my own modules :-)

Cheers,
Denis

**Comment by rvosa** [comment]
Oh really? Nice to hear, what modules are they?

You're right, though, I do need to do some maintenance. I've also added
quite a bit of functionality since the publication so I'm debating if I
should write a Bio::Phylo 2.0 manuscript.

**Comment by dbaurain** [comment]
Yes, but they are not yet publicly released due to still evolving API and incomplete documentation. :-(

Anyway, there is a fairly recent version there:
<https://bitbucket.org/dbaurain/42/>

I think Bio::Phylo is very good. Yet, a few more tutorials and cookbooks would certainly help :-)

Cheers,
Denis

**Comment by rvosa** [comment]
Ah, cool. If there's anything in particular that you could point out in
terms of what is confusing about Bio::Phylo I'd love to hear it. Obviously
I have a blind spot. I have gathered from workshops and such that the
inheritance tree is not the most intuitive thing in the world when you're
looking for docs, anything else that really doesn't make sense?
