### ISSUE TITLE
NBA client code

### ISSUE THREAD

**Issue by rvosa** [rvosa/bio-phylo#39]
Would be nice to have PhyloWS compatible client code for the Naturalis API.

**Comment by hettling** [comment]
Talk about it tomorrow in the Gebruikersoverleg?

**Comment by rvosa** [comment]
Potentially. The main challenge on my side is to represent whatever is returned by the NBA as species data using Bio::Phylo object annotations. In principle that's doable, but it would be nice to have some agreement about whether property names (and certain property values) are in fact part of some sort of controlled vocabulary. For me more important to understand, though I haven't done my homework in this respect, is whether it is (going to be) possible to query for specimens by geological era. See you tomorrow!
