### ISSUE TITLE
t/26-dom.t fails (with newest XML::LibXML?)

### ISSUE THREAD

**Issue by eserte** [rvosa/bio-phylo#40]
On some of my smoker systems the test suite fails:
```
#   Failed test 'number of nex:nexml elements correct (0)'
#   at t/26-dom.t line 109.
#          got: '0'
#     expected: '1'
# Looks like you failed 1 test of 80.
t/26-dom.t .............. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/80 subtests 
	(less 6 skipped subtests: 73 okay)
```

This seems to happen if XML::LibXML 2.0131 (and probaly 2.0130) is installed. The test passes with XML::LibXML 2.0129 (@shlomif: FYI).

**Comment by hlapp** [comment]
FYI, this issue currently causes all rebuilds of the [bioperl/bioperl Docker container](https://hub.docker.com/r/bioperl/bioperl) to [fail](https://hub.docker.com/r/bioperl/bioperl/builds/biavtxsffutrhlnolcvu2uv/). Is there a plan for resolution? If not, I will probably need to remove Bio::Phylo from the container build, which would be unfortunate.

**Comment by shlomif** [comment]
On Sun, 29 Oct 2017 19:04:35 -0700
Hilmar Lapp <notifications@github.com> wrote:

> FYI, this issue currently causes all rebuilds of the [bioperl/bioperl Docker
> container](https://hub.docker.com/r/bioperl/bioperl) to
> [fail](https://hub.docker.com/r/bioperl/bioperl/builds/biavtxsffutrhlnolcvu2uv/).
> Is there a plan for resolution? If not, I will probably need to remove
> Bio::Phylo from the container build, which would be unfortunate.
> 

Please try it with XML-LibXML-2.0132 - it may be fixed there.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Understand what Open Source is - http://shlom.in/oss-fs

I’d do Windows-- , but this may result in an integer underflow.
    — an Israeli Linuxer.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by rvosa** [comment]
There seems to be an inconsistency in how XML::LibXML returns element names: in some versions these are NCNames (e.g. `nexml`), in others they have a prefix (e.g. `nex:nexml`). I think I will modify the unit test to deal with this (the test is a bit silly anyway).

**Comment by hlapp** [comment]
> Please try it with XML-LibXML-2.0132 - it may be fixed there.

I saw you updated the release on CPAN, so I went ahead and rebuilt the bioperl-deps container, where [XML::LibXML gets installed](https://github.com/bioperl/bioperl-docker/blob/master/bioperl-deps/Dockerfile#L72). The build [succeeded](https://hub.docker.com/r/bioperl/bioperl-deps/builds/bwvwnvt7abja5nfvesuajgv/), and if I install Bio::Phylo locally in that container it succeeds. 

The bioperl-deps rebuild succeeding also triggered the bioperl/bioperl:latest and :stable containers to rebuild on Docker Hub, and both now [succeeded](https://hub.docker.com/r/bioperl/bioperl/builds/bbkmtqbbhuh8tvfgouux9hk/). So I think we're good now.

**Comment by shlomif** [comment]
On Mon, 30 Oct 2017 14:36:12 +0000 (UTC)
Hilmar Lapp <notifications@github.com> wrote:

> > Please try it with XML-LibXML-2.0132 - it may be fixed there.  
> 
> I saw you updated the release on CPAN, so I went ahead and rebuilt the
> bioperl-deps container, where [XML::LibXML gets
> installed](https://github.com/bioperl/bioperl-docker/blob/master/bioperl-deps/Dockerfile#L72).
> The build
> [succeeded](https://hub.docker.com/r/bioperl/bioperl-deps/builds/bwvwnvt7abja5nfvesuajgv/),
> and if I install Bio::Phylo locally in that container it succeeds. 
> 
> The bioperl-deps rebuild succeeding also triggered the bioperl/bioperl:latest
> and :stable containers to rebuild on Docker Hub, and both now
> [succeeded](https://hub.docker.com/r/bioperl/bioperl/builds/bbkmtqbbhuh8tvfgouux9hk/).
> So I think we're good now. 
> 

Great! Thanks for letting me know.


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Text Editors and IDEs - http://shlom.in/IDEs

Question: What is the difference between Chuck Norris and God?
Answer: Chuck Norris knows he isn’t God.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .
